// src/data/addOnServices.ts

import { AddOnService } from '../types/service';

export const addOnServices: AddOnService[] = [
  {
    id: 'addon-interior-vacuum',
    title: 'Interior Vacuum',
    description: 'Thorough vacuuming of seats, carpets, and floor mats to remove dust and debris.',
    image: 'https://images.autoassist.in/addons/interior-vacuum.jpg',
    price: 299,
    duration: '20-30 mins',
    category: 'Cleaning',
    rating: 4.4,
    reviews: 3241,
    recommended: true,
  },
  {
    id: 'addon-foam-wash',
    title: 'Foam Wash',
    description: 'Deep-cleaning foam wash that removes grime while being gentle on your car\u2019s paint.',
    image: 'https://images.autoassist.in/addons/foam-wash.jpg',
    price: 499,
    duration: '30-40 mins',
    category: 'Cleaning',
    rating: 4.5,
    reviews: 4532,
    recommended: true,
  },
  {
    id: 'addon-ceramic-coating',
    title: 'Ceramic Coating',
    description: 'Long-lasting protective coating that adds gloss and shields paint from UV and stains.',
    image: 'https://images.autoassist.in/addons/ceramic-coating.jpg',
    price: 8999,
    duration: '5-6 hrs',
    category: 'Protection',
    rating: 4.7,
    reviews: 1123,
    recommended: true,
  },
  {
    id: 'addon-engine-bay-cleaning',
    title: 'Engine Bay Cleaning',
    description: 'Safe degreasing and cleaning of the engine bay to remove dirt, oil, and grime buildup.',
    image: 'https://images.autoassist.in/addons/engine-bay-cleaning.jpg',
    price: 699,
    duration: '30-45 mins',
    category: 'Cleaning',
    rating: 4.3,
    reviews: 987,
    recommended: false,
  },
  {
    id: 'addon-ac-disinfection',
    title: 'AC Disinfection',
    description: 'Removes bacteria, mold, and odor-causing particles from the AC system for cleaner cabin air.',
    image: 'https://images.autoassist.in/addons/ac-disinfection.jpg',
    price: 599,
    duration: '20-30 mins',
    category: 'AC Care',
    rating: 4.5,
    reviews: 2765,
    recommended: true,
  },
  {
    id: 'addon-nitrogen-filling',
    title: 'Nitrogen Filling',
    description: 'Replaces regular air with nitrogen for more stable tyre pressure and better fuel efficiency.',
    image: 'https://images.autoassist.in/addons/nitrogen-filling.jpg',
    price: 399,
    duration: '15-20 mins',
    category: 'Tyre Care',
    rating: 4.4,
    reviews: 3456,
    recommended: false,
  },
  {
    id: 'addon-headlight-restoration',
    title: 'Headlight Restoration',
    description: 'Restores clarity to foggy or yellowed headlights for improved night visibility.',
    image: 'https://images.autoassist.in/addons/headlight-restoration.jpg',
    price: 899,
    duration: '30-40 mins',
    category: 'Body Care',
    rating: 4.4,
    reviews: 1234,
    recommended: false,
  },
  {
    id: 'addon-wheel-polishing',
    title: 'Wheel Polishing',
    description: 'Polishing and shining of alloy wheels to restore their original luster.',
    image: 'https://images.autoassist.in/addons/wheel-polishing.jpg',
    price: 499,
    duration: '20-30 mins',
    category: 'Body Care',
    rating: 4.3,
    reviews: 876,
    recommended: false,
  },
  {
    id: 'addon-windshield-treatment',
    title: 'Windshield Treatment',
    description: 'Water-repellent coating applied to the windshield for better visibility during rain.',
    image: 'https://images.autoassist.in/addons/windshield-treatment.jpg',
    price: 599,
    duration: '15-20 mins',
    category: 'Protection',
    rating: 4.5,
    reviews: 1543,
    recommended: true,
  },
];