// src/data/batteryBrands.ts
//
// Battery brand catalogue for the Battery Replacement flow.
// Every brand is linked back to the "battery_replacement" service via serviceId,
// so screens can filter this list purely by that id instead of switch cases.

import { BatteryBrand } from "../types/service";

export const batteryBrands: BatteryBrand[] = [
  {
    serviceId: "battery_replacement",
    brandId: "exide",
    brandName: "Exide",
    country: "India",
    description: "India's most trusted battery brand, known for reliable starting power and wide service network.",
    logo: "https://cdn.autoassist.app/brands/exide.png",
    options: [
      {
        batteryModel: "Exide Mileage MREDIN38B20L",
        capacity: "35 Ah",
        voltage: "12V",
        technology: "Lead Acid",
        price: 3499,
        installationCharge: 199,
        totalPrice: 3698,
        warranty: "42 months (18 full + 24 pro-rata)",
        rating: 4.4,
        reviews: 2186,
        recommended: true,
        compatibleCars: ["Maruti Alto", "Maruti Wagon R", "Hyundai Santro", "Tata Tiago"],
        availability: "Same day",
        inStock: true,
      },
      {
        batteryModel: "Exide Matrix MTRED-DIN44",
        capacity: "44 Ah",
        voltage: "12V",
        technology: "Lead Acid",
        price: 4899,
        installationCharge: 199,
        totalPrice: 5098,
        warranty: "42 months (18 full + 24 pro-rata)",
        rating: 4.5,
        reviews: 1542,
        recommended: false,
        compatibleCars: ["Hyundai i10", "Hyundai i20", "Maruti Swift", "Honda Amaze"],
        availability: "Same day",
        inStock: true,
      },
    ],
  },
  {
    serviceId: "battery_replacement",
    brandId: "amaron",
    brandName: "Amaron",
    country: "India",
    description: "Zero maintenance batteries with high cranking power, popular for sedans and SUVs.",
    logo: "https://cdn.autoassist.app/brands/amaron.png",
    options: [
      {
        batteryModel: "Amaron Go DIN40",
        capacity: "35 Ah",
        voltage: "12V",
        technology: "Lead Acid",
        price: 3299,
        installationCharge: 199,
        totalPrice: 3498,
        warranty: "36 months (18 full + 18 pro-rata)",
        rating: 4.3,
        reviews: 1897,
        recommended: false,
        compatibleCars: ["Maruti Alto", "Maruti Celerio", "Renault Kwid"],
        availability: "Same day",
        inStock: true,
      },
      {
        batteryModel: "Amaron Hi-Life DIN44R",
        capacity: "44 Ah",
        voltage: "12V",
        technology: "Enhanced Flooded Battery",
        price: 5199,
        installationCharge: 199,
        totalPrice: 5398,
        warranty: "48 months (24 full + 24 pro-rata)",
        rating: 4.6,
        reviews: 2310,
        recommended: true,
        compatibleCars: ["Honda City", "Hyundai Verna", "Skoda Slavia"],
        availability: "Next day",
        inStock: true,
      },
    ],
  },
  {
    serviceId: "battery_replacement",
    brandId: "livguard",
    brandName: "Livguard",
    country: "India",
    description: "Value-for-money batteries with strong after-sales support across tier 2 and tier 3 cities.",
    logo: "https://cdn.autoassist.app/brands/livguard.png",
    options: [
      {
        batteryModel: "Livguard LGZ40L",
        capacity: "38 Ah",
        voltage: "12V",
        technology: "Lead Acid",
        price: 3099,
        installationCharge: 199,
        totalPrice: 3298,
        warranty: "36 months (18 full + 18 pro-rata)",
        rating: 4.1,
        reviews: 764,
        recommended: false,
        compatibleCars: ["Maruti Alto", "Datsun redi-GO", "Tata Tiago"],
        availability: "Next day",
        inStock: true,
      },
    ],
  },
  {
    serviceId: "battery_replacement",
    brandId: "bosch",
    brandName: "Bosch",
    country: "Germany",
    description: "German-engineered batteries offering high durability and consistent performance in extreme weather.",
    logo: "https://cdn.autoassist.app/brands/bosch.png",
    options: [
      {
        batteryModel: "Bosch S4 DIN45",
        capacity: "45 Ah",
        voltage: "12V",
        technology: "Enhanced Flooded Battery",
        price: 5799,
        installationCharge: 249,
        totalPrice: 6048,
        warranty: "36 months (24 full + 12 pro-rata)",
        rating: 4.5,
        reviews: 1103,
        recommended: true,
        compatibleCars: ["Volkswagen Polo", "Skoda Rapid", "Honda City"],
        availability: "Next day",
        inStock: true,
      },
      {
        batteryModel: "Bosch S6 DIN60",
        capacity: "60 Ah",
        voltage: "12V",
        technology: "AGM (Start-Stop)",
        price: 9499,
        installationCharge: 249,
        totalPrice: 9748,
        warranty: "36 months (24 full + 12 pro-rata)",
        rating: 4.7,
        reviews: 421,
        recommended: false,
        compatibleCars: ["Toyota Innova Crysta", "Mahindra XUV700", "Skoda Kushaq"],
        availability: "2-3 days",
        inStock: false,
      },
    ],
  },
  {
    serviceId: "battery_replacement",
    brandId: "sf_sonic",
    brandName: "SF Sonic",
    country: "India",
    description: "Manufactured by Exide's sister brand, offering budget-friendly options with dependable performance.",
    logo: "https://cdn.autoassist.app/brands/sf-sonic.png",
    options: [
      {
        batteryModel: "SF Sonic FLO FL-DIN42",
        capacity: "42 Ah",
        voltage: "12V",
        technology: "Lead Acid",
        price: 3699,
        installationCharge: 199,
        totalPrice: 3898,
        warranty: "40 months (18 full + 22 pro-rata)",
        rating: 4.2,
        reviews: 986,
        recommended: false,
        compatibleCars: ["Hyundai Grand i10", "Maruti Swift", "Tata Altroz"],
        availability: "Same day",
        inStock: true,
      },
    ],
  },
];