// src/data/carWashPackages.ts
//
// Car wash and detailing packages for the "car_wash" service.
// Ordered roughly from lightest to most premium so it renders well as a list.

import { CarWashPackage } from "../types/service";

export const carWashPackages: CarWashPackage[] = [
  {
    serviceId: "car_wash",
    packageId: "basic_wash",
    title: "Basic Wash",
    description: "A quick exterior wash to clear everyday dust and grime.",
    image: "https://cdn.autoassist.app/washes/basic-wash.jpg",
    duration: "20 mins",
    price: 199,
    discountPrice: 149,
    rating: 4.1,
    reviews: 3421,
    recommended: false,
    included: ["Exterior water wash", "Dry wipe", "Tyre dressing"],
    excluded: ["Interior vacuuming", "Dashboard polish", "Foam wash"],
  },
  {
    serviceId: "car_wash",
    packageId: "foam_wash",
    title: "Foam Wash",
    description: "Foam-based exterior wash that lifts dirt without scratching the paint.",
    image: "https://cdn.autoassist.app/washes/foam-wash.jpg",
    duration: "30 mins",
    price: 349,
    discountPrice: 299,
    rating: 4.3,
    reviews: 2678,
    recommended: false,
    included: ["Foam shampoo wash", "Exterior rinse", "Dry wipe", "Tyre dressing"],
    excluded: ["Interior vacuuming", "Wax coating"],
  },
  {
    serviceId: "car_wash",
    packageId: "premium_wash",
    title: "Premium Wash",
    description: "Exterior foam wash plus a quick interior vacuum for a fresher cabin.",
    image: "https://cdn.autoassist.app/washes/premium-wash.jpg",
    duration: "45 mins",
    price: 599,
    discountPrice: 499,
    rating: 4.5,
    reviews: 4109,
    recommended: true,
    included: ["Foam shampoo wash", "Interior vacuuming", "Dashboard wipe", "Tyre dressing", "Door jamb cleaning"],
    excluded: ["Steam cleaning", "Ceramic coating"],
  },
  {
    serviceId: "car_wash",
    packageId: "steam_wash",
    title: "Steam Wash",
    description: "Waterless steam-based wash, ideal for societies with water restrictions.",
    image: "https://cdn.autoassist.app/washes/steam-wash.jpg",
    duration: "35 mins",
    price: 449,
    discountPrice: 399,
    rating: 4.2,
    reviews: 1532,
    recommended: false,
    included: ["Steam exterior cleaning", "Microfiber dry wipe", "Tyre dressing"],
    excluded: ["Interior vacuuming", "Underbody wash"],
  },
  {
    serviceId: "car_wash",
    packageId: "interior_detailing",
    title: "Interior Detailing",
    description: "Deep cleaning of seats, carpets, and dashboard to remove stains and odour.",
    image: "https://cdn.autoassist.app/washes/interior-detailing.jpg",
    duration: "90 mins",
    price: 1799,
    discountPrice: 1499,
    rating: 4.6,
    reviews: 987,
    recommended: false,
    included: ["Seat shampooing", "Carpet shampooing", "Dashboard polish", "AC vent cleaning", "Odour treatment"],
    excluded: ["Exterior wash", "Engine bay cleaning"],
  },
  {
    serviceId: "car_wash",
    packageId: "exterior_detailing",
    title: "Exterior Detailing",
    description: "Clay bar treatment and machine polish to restore paint shine.",
    image: "https://cdn.autoassist.app/washes/exterior-detailing.jpg",
    duration: "120 mins",
    price: 2499,
    discountPrice: 2099,
    rating: 4.6,
    reviews: 743,
    recommended: false,
    included: ["Clay bar treatment", "Machine polish", "Headlight restoration", "Tyre and trim dressing"],
    excluded: ["Interior vacuuming", "Ceramic coating"],
  },
  {
    serviceId: "car_wash",
    packageId: "ceramic_wash",
    title: "Ceramic Wash",
    description: "Foam wash finished with a spray ceramic sealant for a glossy, water-repellent coat.",
    image: "https://cdn.autoassist.app/washes/ceramic-wash.jpg",
    duration: "60 mins",
    price: 999,
    discountPrice: 849,
    rating: 4.5,
    reviews: 612,
    recommended: false,
    included: ["Foam shampoo wash", "Spray ceramic sealant", "Tyre dressing", "Glass coating"],
    excluded: ["Interior detailing", "Paint correction"],
  },
  {
    serviceId: "car_wash",
    packageId: "complete_detailing",
    title: "Complete Detailing",
    description: "The full package — interior deep clean, exterior polish, and ceramic protection in one visit.",
    image: "https://cdn.autoassist.app/washes/complete-detailing.jpg",
    duration: "180 mins",
    price: 4999,
    discountPrice: 4299,
    rating: 4.8,
    reviews: 358,
    recommended: true,
    included: [
      "Seat and carpet shampooing",
      "Dashboard and AC vent cleaning",
      "Clay bar treatment and machine polish",
      "Ceramic sealant coating",
      "Engine bay cleaning",
    ],
    excluded: ["Paint respray", "Dent removal"],
  },
];