// src/data/dentPaintServices.ts
//
// Panel-level dent and paint services for the "dent_paint" service.
// Kept per-panel (not bundled) so the user can pick exactly which parts of
// the car need work, and pricing can be summed across selected panels.

import { DentPaintPanel } from "../types/service";

export const dentPaintServices: DentPaintPanel[] = [
  {
    serviceId: "dent_paint",
    panelId: "front_bumper",
    title: "Front Bumper",
    price: 2499,
    duration: "1 day",
    paintWarranty: "12 months",
    rating: 4.4,
    reviews: 1204,
    recommended: true,
    included: ["Dent removal", "Primer coat", "Colour matched paint", "Clear coat and buffing"],
    excluded: ["Bumper replacement", "Sensor recalibration"],
  },
  {
    serviceId: "dent_paint",
    panelId: "rear_bumper",
    title: "Rear Bumper",
    price: 2499,
    duration: "1 day",
    paintWarranty: "12 months",
    rating: 4.4,
    reviews: 1092,
    recommended: false,
    included: ["Dent removal", "Primer coat", "Colour matched paint", "Clear coat and buffing"],
    excluded: ["Bumper replacement", "Parking sensor recalibration"],
  },
  {
    serviceId: "dent_paint",
    panelId: "bonnet",
    title: "Bonnet",
    price: 3499,
    duration: "1-2 days",
    paintWarranty: "12 months",
    rating: 4.3,
    reviews: 687,
    recommended: false,
    included: ["Dent pulling", "Surface levelling", "Primer coat", "Colour matched paint"],
    excluded: ["Hinge replacement", "Insulation pad replacement"],
  },
  {
    serviceId: "dent_paint",
    panelId: "roof",
    title: "Roof",
    price: 3999,
    duration: "1-2 days",
    paintWarranty: "12 months",
    rating: 4.2,
    reviews: 341,
    recommended: false,
    included: ["Dent pulling", "Surface levelling", "Primer coat", "Colour matched paint"],
    excluded: ["Sunroof mechanism repair"],
  },
  {
    serviceId: "dent_paint",
    panelId: "boot",
    title: "Boot",
    price: 3299,
    duration: "1-2 days",
    paintWarranty: "12 months",
    rating: 4.3,
    reviews: 452,
    recommended: false,
    included: ["Dent pulling", "Primer coat", "Colour matched paint", "Clear coat and buffing"],
    excluded: ["Boot lock replacement", "Wiring repair"],
  },
  {
    serviceId: "dent_paint",
    panelId: "front_left_door",
    title: "Front Left Door",
    price: 2899,
    duration: "1 day",
    paintWarranty: "12 months",
    rating: 4.4,
    reviews: 798,
    recommended: false,
    included: ["Dent removal", "Primer coat", "Colour matched paint", "Clear coat and buffing"],
    excluded: ["Door mechanism repair", "Window motor replacement"],
  },
  {
    serviceId: "dent_paint",
    panelId: "front_right_door",
    title: "Front Right Door",
    price: 2899,
    duration: "1 day",
    paintWarranty: "12 months",
    rating: 4.4,
    reviews: 812,
    recommended: false,
    included: ["Dent removal", "Primer coat", "Colour matched paint", "Clear coat and buffing"],
    excluded: ["Door mechanism repair", "Window motor replacement"],
  },
  {
    serviceId: "dent_paint",
    panelId: "rear_left_door",
    title: "Rear Left Door",
    price: 2799,
    duration: "1 day",
    paintWarranty: "12 months",
    rating: 4.3,
    reviews: 564,
    recommended: false,
    included: ["Dent removal", "Primer coat", "Colour matched paint", "Clear coat and buffing"],
    excluded: ["Door mechanism repair"],
  },
  {
    serviceId: "dent_paint",
    panelId: "rear_right_door",
    title: "Rear Right Door",
    price: 2799,
    duration: "1 day",
    paintWarranty: "12 months",
    rating: 4.3,
    reviews: 571,
    recommended: false,
    included: ["Dent removal", "Primer coat", "Colour matched paint", "Clear coat and buffing"],
    excluded: ["Door mechanism repair"],
  },
  {
    serviceId: "dent_paint",
    panelId: "left_fender",
    title: "Left Fender",
    price: 2299,
    duration: "1 day",
    paintWarranty: "12 months",
    rating: 4.3,
    reviews: 389,
    recommended: false,
    included: ["Dent removal", "Primer coat", "Colour matched paint", "Clear coat and buffing"],
    excluded: ["Wheel arch liner replacement"],
  },
  {
    serviceId: "dent_paint",
    panelId: "right_fender",
    title: "Right Fender",
    price: 2299,
    duration: "1 day",
    paintWarranty: "12 months",
    rating: 4.3,
    reviews: 402,
    recommended: false,
    included: ["Dent removal", "Primer coat", "Colour matched paint", "Clear coat and buffing"],
    excluded: ["Wheel arch liner replacement"],
  },
  {
    serviceId: "dent_paint",
    panelId: "quarter_panel",
    title: "Quarter Panel",
    price: 3799,
    duration: "1-2 days",
    paintWarranty: "12 months",
    rating: 4.2,
    reviews: 218,
    recommended: false,
    included: ["Dent pulling", "Panel beating", "Primer coat", "Colour matched paint"],
    excluded: ["Structural panel replacement"],
  },
  {
    serviceId: "dent_paint",
    panelId: "side_mirror",
    title: "Side Mirror",
    price: 899,
    duration: "4-6 hours",
    paintWarranty: "12 months",
    rating: 4.5,
    reviews: 673,
    recommended: false,
    included: ["Housing repair", "Primer coat", "Colour matched paint"],
    excluded: ["Mirror glass replacement", "Indicator light replacement"],
  },
  {
    serviceId: "dent_paint",
    panelId: "full_body_paint",
    title: "Full Body Paint",
    price: 24999,
    duration: "4-5 days",
    paintWarranty: "24 months",
    rating: 4.6,
    reviews: 156,
    recommended: true,
    included: [
      "Complete body denting where needed",
      "Full primer coat",
      "Colour matched paint across all panels",
      "Clear coat and machine buffing",
      "Final quality inspection",
    ],
    excluded: ["Underbody rust treatment", "Interior work"],
  },
];