// src/data/oils.ts

import { OilCategory } from '../types/service';

export const oilCategories: OilCategory[] = [
  {
    id: 'oil-cat-mineral',
    title: 'Mineral',
    description:
      'Budget-friendly engine oil refined directly from crude oil. Suitable for older engines and low-mileage cars.',
    image: 'https://images.autoassist.in/oils/mineral.jpg',
    brands: [
      {
        id: 'oil-castrol-mineral',
        name: 'Castrol GTX',
        image: 'https://images.autoassist.in/oils/castrol-gtx.jpg',
        viscosity: '15W40',
        quantity: '3.5L',
        price: 1299,
        rating: 4.3,
        reviews: 3421,
        compatibleBrands: ['Maruti Suzuki', 'Tata', 'Hyundai', 'Mahindra'],
        description: 'Reliable mineral oil for everyday driving conditions.',
        recommended: false,
      },
      {
        id: 'oil-shell-mineral',
        name: 'Shell Rimula',
        image: 'https://images.autoassist.in/oils/shell-rimula.jpg',
        viscosity: '15W40',
        quantity: '3.5L',
        price: 1349,
        rating: 4.2,
        reviews: 2765,
        compatibleBrands: ['Tata', 'Mahindra', 'Ashok Leyland'],
        description: 'Durable protection for high-mileage engines.',
        recommended: false,
      },
      {
        id: 'oil-servo-mineral',
        name: 'Servo MCO',
        image: 'https://images.autoassist.in/oils/servo-mco.jpg',
        viscosity: '20W40',
        quantity: '3.5L',
        price: 999,
        rating: 4.0,
        reviews: 5123,
        compatibleBrands: ['Maruti Suzuki', 'Tata', 'Hindustan Motors'],
        description: 'Affordable and widely available mineral oil.',
        recommended: false,
      },
    ],
  },
  {
    id: 'oil-cat-semi-synthetic',
    title: 'Semi Synthetic',
    description:
      'A blend of mineral and synthetic oil offering better protection and performance than pure mineral oil.',
    image: 'https://images.autoassist.in/oils/semi-synthetic.jpg',
    brands: [
      {
        id: 'oil-castrol-semi',
        name: 'Castrol Magnatec',
        image: 'https://images.autoassist.in/oils/castrol-magnatec.jpg',
        viscosity: '10W40',
        quantity: '3.5L',
        price: 1899,
        rating: 4.5,
        reviews: 6234,
        compatibleBrands: ['Maruti Suzuki', 'Hyundai', 'Honda', 'Toyota'],
        description: 'Intelligent molecules that cling to engine parts for extra protection.',
        recommended: true,
      },
      {
        id: 'oil-mobil-semi',
        name: 'Mobil Super',
        image: 'https://images.autoassist.in/oils/mobil-super.jpg',
        viscosity: '10W40',
        quantity: '3.5L',
        price: 1799,
        rating: 4.4,
        reviews: 4890,
        compatibleBrands: ['Hyundai', 'Kia', 'Honda', 'Volkswagen'],
        description: 'Balanced formula for improved engine cleanliness.',
        recommended: false,
      },
      {
        id: 'oil-motul-semi',
        name: 'Motul 3000',
        image: 'https://images.autoassist.in/oils/motul-3000.jpg',
        viscosity: '15W50',
        quantity: '3.5L',
        price: 1699,
        rating: 4.3,
        reviews: 2109,
        compatibleBrands: ['Tata', 'Mahindra', 'Renault'],
        description: 'Technosynthese formula for enhanced engine performance.',
        recommended: false,
      },
    ],
  },
  {
    id: 'oil-cat-fully-synthetic',
    title: 'Fully Synthetic',
    description:
      'Premium chemically engineered oil offering maximum engine protection, performance, and fuel efficiency.',
    image: 'https://images.autoassist.in/oils/fully-synthetic.jpg',
    brands: [
      {
        id: 'oil-castrol-full',
        name: 'Castrol Edge',
        image: 'https://images.autoassist.in/oils/castrol-edge.jpg',
        viscosity: '5W30',
        quantity: '3.5L',
        price: 2999,
        rating: 4.8,
        reviews: 9876,
        compatibleBrands: ['BMW', 'Audi', 'Mercedes-Benz', 'Toyota', 'Honda'],
        description: 'Titanium strengthened formula for maximum performance.',
        recommended: true,
      },
      {
        id: 'oil-mobil-full',
        name: 'Mobil 1',
        image: 'https://images.autoassist.in/oils/mobil-1.jpg',
        viscosity: '5W30',
        quantity: '4L',
        price: 3299,
        rating: 4.7,
        reviews: 7654,
        compatibleBrands: ['BMW', 'Audi', 'Volkswagen', 'Ford'],
        description: 'Advanced full synthetic oil trusted by racing teams.',
        recommended: true,
      },
      {
        id: 'oil-motul-full',
        name: 'Motul 8100',
        image: 'https://images.autoassist.in/oils/motul-8100.jpg',
        viscosity: '5W40',
        quantity: '4L',
        price: 3099,
        rating: 4.6,
        reviews: 4321,
        compatibleBrands: ['Honda', 'Toyota', 'Skoda', 'Jeep'],
        description: 'High-performance synthetic oil for modern turbocharged engines.',
        recommended: false,
      },
      {
        id: 'oil-shell-full',
        name: 'Shell Helix Ultra',
        image: 'https://images.autoassist.in/oils/shell-helix-ultra.jpg',
        viscosity: '5W30',
        quantity: '4L',
        price: 3199,
        rating: 4.7,
        reviews: 5432,
        compatibleBrands: ['Mercedes-Benz', 'BMW', 'Hyundai', 'Kia'],
        description: 'PurePlus technology for cleaner, more efficient engines.',
        recommended: true,
      },
    ],
  },
];