// src/data/roadsideServices.ts
//
// Roadside assistance offerings for the "roadside" service.
// Entries with comingSoon: true should render as disabled/greyed out in the UI.

import { RoadsideService } from "../types/service";

export const roadsideServices: RoadsideService[] = [
  {
    serviceId: "roadside",
    id: "battery_jump_start",
    title: "Battery Jump Start",
    description: "A technician reaches your location to jump start a dead battery.",
    iconName: "flash-outline",
    estimatedArrival: "20-30 mins",
    availability: "24/7",
    price: 349,
    comingSoon: false,
  },
  {
    serviceId: "roadside",
    id: "flat_tyre_assistance",
    title: "Flat Tyre Assistance",
    description: "On-spot puncture repair or spare tyre fitting to get you moving again.",
    iconName: "disc-outline",
    estimatedArrival: "25-35 mins",
    availability: "24/7",
    price: 299,
    comingSoon: false,
  },
  {
    serviceId: "roadside",
    id: "fuel_delivery",
    title: "Fuel Delivery",
    description: "Emergency petrol or diesel delivered to your location if you run out of fuel.",
    iconName: "water-outline",
    estimatedArrival: "30-40 mins",
    availability: "6:00 AM - 11:00 PM",
    price: 249,
    comingSoon: false,
  },
  {
    serviceId: "roadside",
    id: "emergency_contact",
    title: "Emergency Contact",
    description: "One-tap call to our 24/7 emergency helpline for immediate support.",
    iconName: "call-outline",
    estimatedArrival: "Immediate",
    availability: "24/7",
    price: 0,
    comingSoon: false,
  },
  {
    serviceId: "roadside",
    id: "nearest_workshop",
    title: "Nearest Workshop",
    description: "Find and get directions to the closest partner workshop for major repairs.",
    iconName: "location-outline",
    estimatedArrival: "Instant",
    availability: "24/7",
    price: 0,
    comingSoon: false,
  },
  {
    serviceId: "roadside",
    id: "live_location_sharing",
    title: "Live Location Sharing",
    description: "Share your live location with our support team or a trusted contact during a breakdown.",
    iconName: "navigate-outline",
    estimatedArrival: "Instant",
    availability: "24/7",
    price: 0,
    comingSoon: false,
  },
  {
    serviceId: "roadside",
    id: "tow_truck",
    title: "Tow Truck",
    description: "Flatbed towing to the nearest workshop for vehicles that can't be driven.",
    iconName: "car-outline",
    estimatedArrival: "45-60 mins",
    availability: "24/7",
    price: 1499,
    comingSoon: true,
  },
  {
    serviceId: "roadside",
    id: "accident_recovery",
    title: "Accident Recovery",
    description: "Dedicated recovery support and coordination with insurance after an accident.",
    iconName: "alert-circle-outline",
    estimatedArrival: "45-60 mins",
    availability: "24/7",
    price: 1999,
    comingSoon: true,
  },
];