// src/data/services.ts

import { Service } from "../types/service";

export const services: Service[] = [
  {
    id: "general-service",
    title: "General Service",
    description:
      "A complete top-to-bottom check-up that keeps your car running smoothly. Our certified technicians pick up your vehicle from your doorstep, carry out a thorough general service, and deliver it back spotless.",
    image: "https://images.autoassist.app/services/general-service.jpg",
    category: "General Service",
    price: 1499,
    originalPrice: 1899,
    duration: "3-4 Hours",
    warranty: "1000 Km or 1 Month",
    rating: 4.6,
    reviews: 3421,
    recommended: true,
    popular: true,
    serviceItems: [
      {
        id: "gs-engine-oil",
        title: "Engine Oil Replacement",
        description: "Drain old engine oil and refill with manufacturer-recommended grade oil for smoother performance.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "gs-oil-filter",
        title: "Oil Filter Replacement",
        description: "Replace the oil filter to keep contaminants away from your engine's fresh oil.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "gs-air-filter",
        title: "Air Filter Cleaning",
        description: "Clean and inspect the air filter to maintain optimal engine air intake.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "gs-ac-check",
        title: "AC Cooling Check",
        description: "Inspect AC vents and cooling performance to ensure comfortable rides.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "gs-battery-check",
        title: "Battery Health Check",
        description: "Check battery terminals, charge level, and overall health.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "gs-brake-inspection",
        title: "Brake Inspection",
        description: "Inspect brake pads, discs, and fluid levels for safe, confident stopping power.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "gs-fluid-topup",
        title: "All Fluid Top-up",
        description: "Top up coolant, brake fluid, and windshield washer fluid to recommended levels.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "gs-multi-point",
        title: "21-Point Safety Inspection",
        description: "A detailed inspection across the engine, suspension, electricals, and more.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "gs-car-wash",
        title: "Exterior Car Wash",
        description: "A thorough exterior wash that leaves your car looking freshly detailed.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "gs-interior-vacuum",
        title: "Interior Vacuuming",
        description: "Vacuum seats, mats, and dashboard for a clean, fresh cabin.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "gs-engine-flush",
        title: "Engine Flush",
        description: "Remove sludge build-up from the engine for cleaner, longer-lasting performance.",
        price: 499,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "gs-ac-gas-topup",
        title: "AC Gas Top-up",
        description: "Recharge AC refrigerant for ice-cold cooling all season long.",
        price: 899,
        mandatory: false,
        defaultSelected: false,
      },
    ],
  },
  {
    id: "periodic-service",
    title: "Periodic Service",
    description:
      "Manufacturer-recommended periodic maintenance that keeps your warranty intact and your car performing like new, with doorstep pickup and delivery included.",
    image: "https://images.autoassist.app/services/periodic-service.jpg",
    category: "Periodic Service",
    price: 2999,
    originalPrice: 3599,
    duration: "4-5 Hours",
    warranty: "5000 Km or 3 Months",
    rating: 4.7,
    reviews: 2156,
    recommended: true,
    serviceItems: [
      {
        id: "ps-engine-oil",
        title: "Engine Oil Replacement",
        description: "Replace engine oil with manufacturer-recommended grade oil as per the service schedule.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "ps-oil-filter",
        title: "Oil Filter Replacement",
        description: "Fit a new oil filter to keep the fresh engine oil free of contaminants.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "ps-air-filter-replace",
        title: "Air Filter Replacement",
        description: "Replace the air filter to restore optimal engine breathing and fuel efficiency.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "ps-ac-filter",
        title: "Cabin AC Filter Replacement",
        description: "Fit a new cabin filter for cleaner, fresher air inside the car.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "ps-brake-fluid",
        title: "Brake Fluid Top-up",
        description: "Top up brake fluid to the recommended level for consistent braking performance.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "ps-coolant-check",
        title: "Coolant Level Check",
        description: "Check and top up coolant to prevent engine overheating.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "ps-battery-terminal",
        title: "Battery Terminal Cleaning",
        description: "Clean battery terminals and check charge levels for reliable starts.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "ps-wiper-fluid",
        title: "Wiper Fluid Top-up",
        description: "Top up windshield washer fluid for clear visibility on the road.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "ps-multi-point",
        title: "40-Point Periodic Inspection",
        description: "An in-depth inspection covering engine, electricals, suspension, and safety systems.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "ps-tyre-pressure",
        title: "Tyre Pressure Check",
        description: "Check and set tyre pressure to the recommended level for all four tyres.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "ps-wheel-alignment",
        title: "Wheel Alignment",
        description: "Correct wheel angles for a smoother, safer ride and even tyre wear.",
        price: 599,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "ps-wheel-balancing",
        title: "Wheel Balancing",
        description: "Balance all four wheels to eliminate vibrations at high speed.",
        price: 399,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "ps-engine-flush",
        title: "Engine Flush",
        description: "Deep-clean the engine internals to remove sludge before the fresh oil fill.",
        price: 499,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "ps-fuel-additive",
        title: "Fuel Injector Additive",
        description: "Add a fuel system cleaner to improve combustion and restore lost mileage.",
        price: 349,
        mandatory: false,
        defaultSelected: false,
      },
    ],
  },
  {
    id: "ac-service",
    title: "AC Service",
    description:
      "Beat the heat with a complete AC service. We inspect, clean, and recharge your car's cooling system to restore icy performance, picked up and delivered right to your doorstep.",
    image: "https://images.autoassist.app/services/ac-service.jpg",
    category: "AC Service",
    price: 1299,
    originalPrice: 1599,
    duration: "2-3 Hours",
    warranty: "3 Months",
    rating: 4.5,
    reviews: 1890,
    recommended: false,
    popular: true,
    serviceItems: [
      {
        id: "ac-vent-cleaning",
        title: "AC Vent Cleaning",
        description: "Clean AC vents to improve airflow and remove trapped dust.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "ac-filter-cleaning",
        title: "Cabin Filter Cleaning",
        description: "Clean the cabin filter to improve air quality and cooling efficiency.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "ac-cooling-check",
        title: "Cooling Performance Check",
        description: "Measure vent temperature to confirm the AC is cooling as expected.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "ac-compressor-check",
        title: "Compressor Health Check",
        description: "Inspect the compressor for unusual noise, wear, or performance drop.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "ac-gas-pressure-check",
        title: "Gas Pressure Check",
        description: "Check refrigerant pressure to identify leaks or low gas levels.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "ac-condenser-check",
        title: "Condenser Inspection",
        description: "Inspect the condenser for dirt build-up or physical damage.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "ac-blower-check",
        title: "Blower Motor Check",
        description: "Test the blower motor for consistent airflow at every fan speed.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "ac-leak-test",
        title: "AC Leak Test",
        description: "Run a dye or electronic leak test to catch refrigerant leaks early.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "ac-gas-refill",
        title: "AC Gas Refilling",
        description: "Recharge the AC system with refrigerant for ice-cold, consistent cooling.",
        price: 899,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "ac-cabin-filter-replace",
        title: "Cabin Filter Replacement",
        description: "Fit a brand-new cabin filter for noticeably fresher cabin air.",
        price: 349,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "ac-compressor-oil",
        title: "Compressor Oil Top-up",
        description: "Top up compressor lubricant to protect against premature wear.",
        price: 599,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "ac-ozone-treatment",
        title: "Ozone Disinfection Treatment",
        description: "Eliminate odour-causing bacteria and fungi from the AC system and cabin.",
        price: 799,
        mandatory: false,
        defaultSelected: false,
      },
    ],
  },
  {
    id: "car-wash",
    title: "Car Wash",
    description:
      "A premium hand wash and interior clean that brings back that showroom shine, with free pickup and drop so your car comes back spotless without any effort on your part.",
    image: "https://images.autoassist.app/services/car-wash.jpg",
    category: "Car Wash",
    price: 399,
    originalPrice: 499,
    duration: "45-60 Minutes",
    warranty: "7 Day Shine Guarantee",
    rating: 4.4,
    reviews: 5643,
    recommended: false,
    popular: true,
    serviceItems: [
      {
        id: "cw-exterior-wash",
        title: "Exterior Foam Wash",
        description: "A gentle foam wash that lifts dirt without harming the paint.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "cw-interior-vacuum",
        title: "Interior Vacuuming",
        description: "Vacuum seats, carpets, and boot space for a fresh, clean cabin.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "cw-dashboard-cleaning",
        title: "Dashboard Cleaning",
        description: "Wipe down and polish the dashboard and console for a like-new look.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "cw-tyre-dressing",
        title: "Tyre Dressing",
        description: "Apply tyre shine dressing for a fresh, matte-black finish.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "cw-mats-cleaning",
        title: "Floor Mats Cleaning",
        description: "Deep clean floor mats to remove dust, mud, and stains.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "cw-glass-cleaning",
        title: "Glass & Mirror Cleaning",
        description: "Streak-free cleaning of all windows and mirrors, inside and out.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "cw-door-jamb-cleaning",
        title: "Door Jamb Cleaning",
        description: "Clean often-missed door jambs and edges for a truly complete wash.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "cw-air-freshener",
        title: "Air Freshener Application",
        description: "Finish with a light air freshener for a pleasant-smelling cabin.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "cw-ceramic-coating",
        title: "Ceramic Coating",
        description: "A long-lasting ceramic layer that protects paint and adds a glossy shine.",
        price: 4999,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "cw-interior-sanitization",
        title: "Interior Sanitization",
        description: "Sanitize seats, vents, and touch points to eliminate germs and odours.",
        price: 599,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "cw-engine-bay-cleaning",
        title: "Engine Bay Cleaning",
        description: "Safely degrease and clean the engine bay for a tidy, well-kept look.",
        price: 499,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "cw-underbody-wash",
        title: "Underbody Wash",
        description: "Flush out dust, mud, and road grime from the underbody.",
        price: 349,
        mandatory: false,
        defaultSelected: false,
      },
    ],
  },
  {
    id: "wheel-alignment",
    title: "Wheel Alignment",
    description:
      "Precision computerized wheel alignment for a smoother, safer, and more fuel-efficient ride, correcting steering drift and uneven tyre wear.",
    image: "https://images.autoassist.app/services/wheel-alignment.jpg",
    category: "Wheel Care",
    price: 599,
    originalPrice: 799,
    duration: "45 Minutes",
    warranty: "15 Days or 500 Km",
    rating: 4.5,
    reviews: 1245,
    recommended: false,
    serviceItems: [
      {
        id: "wa-camber-check",
        title: "Camber Angle Check",
        description: "Measure camber angle to correct uneven tyre wear.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "wa-caster-check",
        title: "Caster Angle Check",
        description: "Check caster angle for stable, predictable steering feel.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "wa-toe-adjustment",
        title: "Toe Adjustment",
        description: "Adjust toe angle to prevent steering drift and premature tyre wear.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "wa-steering-check",
        title: "Steering Alignment Check",
        description: "Verify steering wheel centering after alignment corrections.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "wa-tyre-inspection",
        title: "Tyre Wear Inspection",
        description: "Inspect tread wear patterns to catch alignment issues early.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "wa-suspension-check",
        title: "Suspension Health Check",
        description: "Check suspension components that affect alignment accuracy.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "wa-computerized-alignment",
        title: "Computerized Wheel Alignment",
        description: "Precision alignment using computerized imaging for accurate results.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "wa-test-drive",
        title: "Post-Service Test Drive",
        description: "A short test drive to confirm straight-line stability after alignment.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "wa-wheel-balancing",
        title: "Wheel Balancing",
        description: "Balance all four wheels to remove vibrations at high speed.",
        price: 399,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "wa-nitrogen-filling",
        title: "Nitrogen Filling",
        description: "Fill tyres with nitrogen for more stable pressure and cooler running.",
        price: 299,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "wa-tyre-rotation",
        title: "Tyre Rotation",
        description: "Rotate tyres to promote even tread wear and extend tyre life.",
        price: 249,
        mandatory: false,
        defaultSelected: false,
      },
    ],
  },
  {
    id: "wheel-balancing",
    title: "Wheel Balancing",
    description:
      "Eliminate steering vibrations and uneven tyre wear with precision wheel balancing on the latest computerized equipment.",
    image: "https://images.autoassist.app/services/wheel-balancing.jpg",
    category: "Wheel Care",
    price: 399,
    originalPrice: 549,
    duration: "30-40 Minutes",
    warranty: "15 Days or 500 Km",
    rating: 4.4,
    reviews: 987,
    recommended: false,
    serviceItems: [
      {
        id: "wb-wheel-inspection",
        title: "Wheel Inspection",
        description: "Inspect all four wheels for damage before balancing.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "wb-weight-check",
        title: "Wheel Weight Check",
        description: "Check and remove old or loose wheel weights.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "wb-computerized-balancing",
        title: "Computerized Balancing",
        description: "Balance each wheel precisely using computerized equipment.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "wb-vibration-test",
        title: "Vibration Test",
        description: "Test for vibrations at speed to confirm balancing accuracy.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "wb-tyre-pressure-check",
        title: "Tyre Pressure Check",
        description: "Set tyre pressure to the recommended level on all four tyres.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "wb-rim-inspection",
        title: "Rim Damage Inspection",
        description: "Check rims for bends or cracks that could affect balancing.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "wb-hub-cleaning",
        title: "Wheel Hub Cleaning",
        description: "Clean wheel hubs for a flush, accurate wheel fitment.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "wb-test-drive",
        title: "Post-Service Test Drive",
        description: "A short test drive to confirm a smooth, vibration-free ride.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "wb-wheel-alignment",
        title: "Wheel Alignment",
        description: "Correct wheel angles for a smoother ride and even tyre wear.",
        price: 599,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "wb-nitrogen-filling",
        title: "Nitrogen Filling",
        description: "Fill tyres with nitrogen for more stable pressure and cooler running.",
        price: 299,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "wb-tyre-rotation",
        title: "Tyre Rotation",
        description: "Rotate tyres to promote even tread wear and extend tyre life.",
        price: 249,
        mandatory: false,
        defaultSelected: false,
      },
    ],
  },
  {
    id: "oil-change",
    title: "Oil Change",
    description:
      "A quick and thorough engine oil change using premium-grade oil to keep your engine running smoothly between full services.",
    image: "https://images.autoassist.app/services/oil-change.jpg",
    category: "Oil Change",
    price: 899,
    originalPrice: 1099,
    duration: "45-60 Minutes",
    warranty: "1000 Km or 1 Month",
    rating: 4.6,
    reviews: 2765,
    recommended: true,
    serviceItems: [
      {
        id: "oc-oil-drain",
        title: "Old Oil Draining",
        description: "Fully drain old engine oil from the sump.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "oc-oil-refill",
        title: "Engine Oil Refill",
        description: "Refill with fresh, manufacturer-recommended grade engine oil.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "oc-oil-filter-replace",
        title: "Oil Filter Replacement",
        description: "Fit a new oil filter alongside the fresh oil fill.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "oc-oil-level-check",
        title: "Oil Level Check",
        description: "Confirm oil is filled to the correct level after the change.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "oc-leak-check",
        title: "Oil Leak Inspection",
        description: "Check for oil leaks around the engine and drain plug.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "oc-drain-plug-check",
        title: "Drain Plug & Gasket Check",
        description: "Inspect the drain plug and gasket to prevent future leaks.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "oc-engine-bay-wipe",
        title: "Engine Bay Wipe Down",
        description: "Wipe down the engine bay to remove any spilled oil residue.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "oc-disposal",
        title: "Eco-friendly Oil Disposal",
        description: "Dispose of old oil responsibly at a certified recycling facility.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "oc-engine-flush",
        title: "Engine Flush",
        description: "Remove internal sludge build-up before the fresh oil fill.",
        price: 499,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "oc-oil-additive",
        title: "Oil Additive Treatment",
        description: "Add a protective additive for smoother, quieter engine performance.",
        price: 299,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "oc-air-filter-replace",
        title: "Air Filter Replacement",
        description: "Fit a fresh air filter for improved combustion efficiency.",
        price: 349,
        mandatory: false,
        defaultSelected: false,
      },
    ],
  },
  {
    id: "tyre-replacement",
    title: "Tyre Replacement",
    description:
      "Upgrade to new tyres with expert fitting, balancing, and valve replacement, delivered and fitted right at your doorstep.",
    image: "https://images.autoassist.app/services/tyre-replacement.jpg",
    category: "Tyres",
    price: 3499,
    originalPrice: 3999,
    duration: "30-40 Minutes",
    warranty: "6 Months on Fitting",
    rating: 4.5,
    reviews: 1543,
    recommended: false,
    serviceItems: [
      {
        id: "tyr-old-tyre-removal",
        title: "Old Tyre Removal",
        description: "Safely remove the old, worn tyre from the wheel.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "tyr-new-tyre-fitting",
        title: "New Tyre Fitting",
        description: "Fit the new tyre securely with precision equipment.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "tyr-valve-replacement",
        title: "Valve Replacement",
        description: "Replace the tyre valve to prevent slow air leaks.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "tyr-wheel-balancing-basic",
        title: "Wheel Balancing",
        description: "Balance the wheel after fitting for a smooth, vibration-free ride.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "tyr-pressure-setting",
        title: "Tyre Pressure Setting",
        description: "Set tyre pressure to the manufacturer-recommended level.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "tyr-disposal",
        title: "Old Tyre Disposal",
        description: "Responsibly dispose of the old tyre after replacement.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "tyr-visual-inspection",
        title: "Rim & Wheel Inspection",
        description: "Check the rim and wheel for damage before fitting the new tyre.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "tyr-test-drive",
        title: "Post-Fitting Test Drive",
        description: "A short test drive to confirm a smooth, stable ride.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "tyr-wheel-alignment",
        title: "Wheel Alignment",
        description: "Align all four wheels for even wear on your new tyres.",
        price: 599,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "tyr-nitrogen-filling",
        title: "Nitrogen Filling",
        description: "Fill new tyres with nitrogen for stable pressure and cooler running.",
        price: 299,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "tyr-spare-tyre-check",
        title: "Spare Tyre Check",
        description: "Inspect the spare tyre's condition and pressure for emergencies.",
        price: 149,
        mandatory: false,
        defaultSelected: false,
      },
    ],
  },
  {
    id: "battery-replacement",
    title: "Battery Replacement",
    description:
      "Get a reliable new battery fitted at your doorstep, with free old battery disposal and a hassle-free warranty.",
    image: "https://images.autoassist.app/services/battery-replacement.jpg",
    category: "Battery",
    price: 4499,
    originalPrice: 5499,
    duration: "20-30 Minutes",
    warranty: "1 Year on Battery",
    rating: 4.6,
    reviews: 1876,
    recommended: false,
    serviceItems: [
      {
        id: "bat-old-removal",
        title: "Old Battery Removal",
        description: "Safely disconnect and remove the old battery.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "bat-new-fitting",
        title: "New Battery Fitting",
        description: "Fit and securely connect the new battery.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "bat-terminal-cleaning",
        title: "Terminal Cleaning",
        description: "Clean battery terminals to ensure a strong, corrosion-free connection.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "bat-voltage-check",
        title: "Voltage Check",
        description: "Test the new battery's voltage and charge level after fitting.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "bat-alternator-check",
        title: "Alternator Output Check",
        description: "Check alternator output to confirm the battery will charge correctly.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "bat-connection-check",
        title: "Connection Tightening",
        description: "Tighten all connections to prevent loose-terminal issues.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "bat-disposal",
        title: "Old Battery Disposal",
        description: "Dispose of the old battery responsibly at a certified facility.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "bat-test-drive",
        title: "Post-Fitting Test",
        description: "Start the car and confirm all electricals work correctly after fitting.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "bat-jump-start-kit",
        title: "Jump Start Kit",
        description: "A compact jump start kit to keep in your car for emergencies.",
        price: 799,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "bat-terminal-protector",
        title: "Terminal Protector Spray",
        description: "Apply a protective spray to slow future terminal corrosion.",
        price: 149,
        mandatory: false,
        defaultSelected: false,
      },
    ],
  },
  {
    id: "dent-paint",
    title: "Dent & Paint",
    description:
      "Restore your car's flawless finish with expert dent removal and colour-matched paint work, with doorstep pickup and delivery for a seamless experience.",
    image: "https://images.autoassist.app/services/dent-paint.jpg",
    category: "Dent & Paint",
    price: 1999,
    originalPrice: 2499,
    duration: "1-2 Days",
    warranty: "6 Months on Paint",
    rating: 4.5,
    reviews: 987,
    recommended: false,
    serviceItems: [
      {
        id: "dp-dent-assessment",
        title: "Dent Assessment",
        description: "Assess the dent's depth and panel damage to plan the repair.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "dp-masking",
        title: "Masking & Surface Prep",
        description: "Mask surrounding panels and prep the surface for repair work.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "dp-panel-repair",
        title: "Panel Repair",
        description: "Reshape and repair the damaged panel to its original form.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "dp-primer-coating",
        title: "Primer Coating",
        description: "Apply primer to prepare the surface for an even paint finish.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "dp-color-matching",
        title: "Colour Matching",
        description: "Match the paint colour precisely to your car's factory shade.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "dp-paint-application",
        title: "Paint Application",
        description: "Apply paint in a controlled environment for a seamless, factory-like finish.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "dp-polishing",
        title: "Post-Paint Polishing",
        description: "Polish the repaired panel to blend seamlessly with the rest of the car.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "dp-quality-check",
        title: "Quality Check",
        description: "A final inspection to confirm colour match, finish, and panel alignment.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "dp-ceramic-coating",
        title: "Ceramic Coating",
        description: "Protect the repaired area and beyond with a long-lasting ceramic layer.",
        price: 4999,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "dp-full-body-polish",
        title: "Full Body Polish",
        description: "Polish the entire car for a uniform, showroom-fresh shine.",
        price: 1499,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "dp-headlight-restoration",
        title: "Headlight Restoration",
        description: "Restore foggy, yellowed headlights to clear, bright condition.",
        price: 599,
        mandatory: false,
        defaultSelected: false,
      },
    ],
  },
  {
    id: "brake-service",
    title: "Brake Service",
    description:
      "Ensure safe, confident stops with a complete brake inspection and service, including pad and fluid checks, carried out right at your doorstep.",
    image: "https://images.autoassist.app/services/brake-service.jpg",
    category: "Brake Service",
    price: 799,
    originalPrice: 999,
    duration: "1-2 Hours",
    warranty: "3 Months or 3000 Km",
    rating: 4.6,
    reviews: 2109,
    recommended: true,
    serviceItems: [
      {
        id: "bs-pad-inspection",
        title: "Brake Pad Inspection",
        description: "Check brake pad thickness and wear on all four wheels.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "bs-disc-inspection",
        title: "Brake Disc Inspection",
        description: "Inspect brake discs for scoring, warping, or excessive wear.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "bs-fluid-check",
        title: "Brake Fluid Check",
        description: "Check brake fluid level and condition for consistent braking feel.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "bs-caliper-check",
        title: "Caliper Check",
        description: "Inspect brake calipers for smooth movement and even pad contact.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "bs-handbrake-check",
        title: "Handbrake Adjustment Check",
        description: "Check handbrake tension and adjust for reliable hold.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "bs-pedal-check",
        title: "Brake Pedal Feel Check",
        description: "Assess pedal firmness and travel for signs of air or fluid issues.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "bs-noise-check",
        title: "Brake Noise Inspection",
        description: "Identify the source of any squealing or grinding brake noise.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "bs-test-drive",
        title: "Post-Service Test Drive",
        description: "A short test drive to confirm smooth, confident braking.",
        price: 0,
        mandatory: true,
        defaultSelected: true,
      },
      {
        id: "bs-pad-replacement",
        title: "Brake Pad Replacement",
        description: "Fit new brake pads for restored stopping power.",
        price: 1499,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "bs-disc-replacement",
        title: "Brake Disc Replacement",
        description: "Replace worn or warped brake discs for safer, smoother braking.",
        price: 2499,
        mandatory: false,
        defaultSelected: false,
      },
      {
        id: "bs-fluid-replacement",
        title: "Brake Fluid Replacement",
        description: "Flush and replace old brake fluid to maintain consistent pedal feel.",
        price: 599,
        mandatory: false,
        defaultSelected: false,
      },
    ],
  },
];