// src/data/tyres.ts

import { TyreBrand } from '../types/service';

export const tyreBrands: TyreBrand[] = [
  {
    brandId: 'tyre-michelin',
    name: 'Michelin',
    image: 'https://images.autoassist.in/tyres/michelin.jpg',
    description: 'French premium tyre brand known for durability and fuel efficiency.',
    countryOfOrigin: 'France',
    options: [
      {
        id: 'michelin-165-80-r14',
        size: '165/80 R14',
        price: 4299,
        warranty: '5 years',
        tubeless: true,
        rating: 4.6,
        reviews: 2134,
        compatibleVehicles: ['Maruti Swift', 'Hyundai Grand i10'],
        inStock: true,
      },
      {
        id: 'michelin-195-65-r15',
        size: '195/65 R15',
        price: 5999,
        warranty: '5 years',
        tubeless: true,
        rating: 4.7,
        reviews: 3421,
        compatibleVehicles: ['Honda City', 'Hyundai Verna'],
        inStock: true,
      },
    ],
  },
  {
    brandId: 'tyre-bridgestone',
    name: 'Bridgestone',
    image: 'https://images.autoassist.in/tyres/bridgestone.jpg',
    description: 'Japanese tyre manufacturer offering strong grip and long tread life.',
    countryOfOrigin: 'Japan',
    options: [
      {
        id: 'bridgestone-175-70-r13',
        size: '175/70 R13',
        price: 3699,
        warranty: '4 years',
        tubeless: true,
        rating: 4.5,
        reviews: 2987,
        compatibleVehicles: ['Maruti Alto', 'Maruti WagonR'],
        inStock: true,
      },
      {
        id: 'bridgestone-205-55-r16',
        size: '205/55 R16',
        price: 6499,
        warranty: '5 years',
        tubeless: true,
        rating: 4.6,
        reviews: 1876,
        compatibleVehicles: ['Skoda Rapid', 'Volkswagen Vento'],
        inStock: true,
      },
    ],
  },
  {
    brandId: 'tyre-mrf',
    name: 'MRF',
    image: 'https://images.autoassist.in/tyres/mrf.jpg',
    description: 'India\u2019s most trusted tyre brand, known for durability on Indian roads.',
    countryOfOrigin: 'India',
    options: [
      {
        id: 'mrf-155-65-r13',
        size: '155/65 R13',
        price: 2799,
        warranty: '4 years',
        tubeless: true,
        rating: 4.4,
        reviews: 5432,
        compatibleVehicles: ['Maruti Alto 800', 'Tata Nano'],
        inStock: true,
      },
      {
        id: 'mrf-185-65-r15',
        size: '185/65 R15',
        price: 4199,
        warranty: '5 years',
        tubeless: true,
        rating: 4.5,
        reviews: 4210,
        compatibleVehicles: ['Maruti Baleno', 'Hyundai i20'],
        inStock: true,
      },
    ],
  },
  {
    brandId: 'tyre-apollo',
    name: 'Apollo',
    image: 'https://images.autoassist.in/tyres/apollo.jpg',
    description: 'Popular Indian tyre brand offering reliable performance at affordable prices.',
    countryOfOrigin: 'India',
    options: [
      {
        id: 'apollo-165-70-r14',
        size: '165/70 R14',
        price: 3199,
        warranty: '4 years',
        tubeless: true,
        rating: 4.3,
        reviews: 3654,
        compatibleVehicles: ['Maruti Swift', 'Tata Tiago'],
        inStock: true,
      },
      {
        id: 'apollo-195-60-r16',
        size: '195/60 R16',
        price: 5199,
        warranty: '5 years',
        tubeless: true,
        rating: 4.4,
        reviews: 2543,
        compatibleVehicles: ['Hyundai Creta', 'Kia Seltos'],
        inStock: true,
      },
    ],
  },
  {
    brandId: 'tyre-ceat',
    name: 'CEAT',
    image: 'https://images.autoassist.in/tyres/ceat.jpg',
    description: 'Homegrown tyre brand offering a wide range for hatchbacks to SUVs.',
    countryOfOrigin: 'India',
    options: [
      {
        id: 'ceat-145-80-r12',
        size: '145/80 R12',
        price: 2399,
        warranty: '3 years',
        tubeless: true,
        rating: 4.2,
        reviews: 1987,
        compatibleVehicles: ['Maruti 800', 'Maruti Alto'],
        inStock: true,
      },
      {
        id: 'ceat-215-60-r16',
        size: '215/60 R16',
        price: 5799,
        warranty: '5 years',
        tubeless: true,
        rating: 4.4,
        reviews: 1654,
        compatibleVehicles: ['Mahindra XUV500', 'Tata Harrier'],
        inStock: true,
      },
    ],
  },
  {
    brandId: 'tyre-goodyear',
    name: 'Goodyear',
    image: 'https://images.autoassist.in/tyres/goodyear.jpg',
    description: 'American tyre brand known for high-speed stability and comfort.',
    countryOfOrigin: 'United States',
    options: [
      {
        id: 'goodyear-185-70-r14',
        size: '185/70 R14',
        price: 4099,
        warranty: '4 years',
        tubeless: true,
        rating: 4.5,
        reviews: 1432,
        compatibleVehicles: ['Honda Amaze', 'Hyundai Aura'],
        inStock: true,
      },
      {
        id: 'goodyear-205-65-r15',
        size: '205/65 R15',
        price: 5399,
        warranty: '5 years',
        tubeless: true,
        rating: 4.6,
        reviews: 987,
        compatibleVehicles: ['Toyota Innova', 'Maruti Ertiga'],
        inStock: true,
      },
    ],
  },
  {
    brandId: 'tyre-yokohama',
    name: 'Yokohama',
    image: 'https://images.autoassist.in/tyres/yokohama.jpg',
    description: 'Japanese performance tyre brand favored for sedans and premium hatchbacks.',
    countryOfOrigin: 'Japan',
    options: [
      {
        id: 'yokohama-195-55-r16',
        size: '195/55 R16',
        price: 6199,
        warranty: '5 years',
        tubeless: true,
        rating: 4.6,
        reviews: 876,
        compatibleVehicles: ['Honda City', 'Skoda Slavia'],
        inStock: true,
      },
      {
        id: 'yokohama-225-45-r17',
        size: '225/45 R17',
        price: 7999,
        warranty: '5 years',
        tubeless: true,
        rating: 4.7,
        reviews: 543,
        compatibleVehicles: ['Volkswagen Virtus', 'Skoda Octavia'],
        inStock: true,
      },
    ],
  },
];